
name: Feature Issue
description: Issue for adding a new feature or changing an existing feature.
title: "<Feature Title>"
labels: ["enhancement"]
projects: ["spe-uob/2025-FMCWRadar"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill in the following information regarding your new issue.
  - type: textarea
    id: feature-details
    attributes:
      label: "Feature Details"
      description: "Describe the details of the feature you are proposing or the details of the change you think needs to be made."
      placeholder: "The feature is..."
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: "Additional Information"
      description: "Add any additional information or screenshots here."
      placeholder: "Also..."
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      description: "Tasks that must be completed before submitting issue."
      options:
        - label: "My description of the issue is detailed."
          required: true
        - label: "I have set all the issue metadata, including: assignee, labels, priority, story points, start date, end date, and milestone"
          required: true
