name: Continuous Deployment

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r model/requirements.txt

      - name: Execute all Jupyter Notebooks
        run: |
          for notebook in $(find . -name '*.ipynb'); do
            notebook_dir=$(dirname "$notebook")
            notebook_base=$(basename "$notebook")
            jupyter nbconvert --to notebook --execute "$notebook" --output "$notebook_base" --output-dir "$notebook_dir"
          done

      - name: Find and move ONNX files to 'models' directory with renamed filenames
        run: |
          mkdir -p models
          find . -name '*.onnx' | while read file; do
            dir_name=$(basename "$(dirname "$file")")
            filename=$(basename "$file")
            if [[ "$filename" =~ \((.*)\) ]]; then
              extra=${BASH_REMATCH[1]}
              newname="models/${dir_name}_${extra}.onnx"
            else
              newname="models/${dir_name}.onnx"
            fi
            mv "$file" "$newname"
          done


      - name: Archive ONNX files
        run: tar -cvf models.tar models/

      - name: Upload ONNX files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: onnx-files
          path: models.tar

  create-release:
    needs: run-notebooks
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download ONNX files artifact
        uses: actions/download-artifact@v4
        with:
          name: onnx-files
          path: .

      - name: Extract ONNX files
        run: |
          mkdir -p models
          tar -xvf models.tar -C models
          ls -R models

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.13
        with:
          tag_name: v${{ github.run_number }}
          name: ONNX Files v${{ github.run_number }}
          body: |
            This release contains all the ONNX files generated by our models.
          draft: false
          prerelease: false
          files: models/**/*.onnx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}